### ISSUE TITLE
REMOVE BUTTON NOT WORKING !!!

### ISSUE THREAD

**Issue by YousefAK009** [majedalmoqbeli/appssender-android-app#7]
I tried to remove the application from my device via your's application and this is didn't work as I expected.

In the old version of Android, that's work fine :)

But in new versions not working :(

Pleasssssssssssssssse it's high priority issue , fix it fast as possible , I neeeeeeeeeeeeeeed it :(

**Comment by YousefAK009** [comment]
Thx for the fast response

**Comment by majedalmoqbeli** [comment]
> Thx for the fast response

thinks for your feedback
